### ISSUE TITLE
Got a value error while rendering face

### ISSUE THREAD

**Issue by lanzer** [ototadana/sd-face-editor#1]
Not sure what I'm doing wrong, but here's the console log.  I'm running today's WebUI build.

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui\scripts\face_editor.py", line 208, in run
    entire_image[
ValueError: could not broadcast input array from shape (364,364,3) into shape (364,364,4)

**Comment by ototadana** [comment]
@lanzer Thanks for your feedback ❤️ 
Fixed.

**Comment by alittleanimal** [comment]
@ototadana hi, I got the same error in the latest version, could you help check this again?

**Comment by ototadana** [comment]
@alittleanimal 
Thanks for trying this script.

Perhaps you are running an older version of [Stable Diffusion Web UI](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
If you are running an older version, try changing to a newer version.
If you run the latest version and still get the same error, please paste Traceback.
