### ISSUE TITLE
After restarting the webui, an error message appears:

### ISSUE THREAD

**Issue by ye-pei-sheng** [ototadana/sd-face-editor#11]
Error loading script: face_editor.py
Traceback (most recent call last):
File "H:\SDW\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "H:\SDW\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 879, in exec_module
File "<frozen importlib._bootstrap_external>", line 1017, in get_code
File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "H:\SDW\stable-diffusion-webui\scripts\face_editor.py", line 75
<title>sd-face-editor/face_editor.py at main · ototadana/sd-face-editor</title>
^
SyntaxError: invalid character '·' (U+00B7)

**Comment by ye-pei-sheng** [comment]
After modifying the title, the following error appears:

Error loading script: face_editor.py
Traceback (most recent call last):
File "H:\SDW\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "H:\SDW\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 879, in exec_module
File "<frozen importlib._bootstrap_external>", line 1017, in get_code
File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "H:\SDW\stable-diffusion-webui\scripts\face_editor.py", line 8
<!DOCTYPE html>
^
SyntaxError: invalid syntax

https://ngabbs.com/read.php?&tid=35947266&pid=683914934&to=1

**Comment by ototadana** [comment]
Thank you for using my script. 
Could you please try using the script downloaded from the following URL:
https://raw.githubusercontent.com/ototadana/sd-face-editor/main/scripts/face_editor.py

**Comment by ye-pei-sheng** [comment]
> @ye-pei-sheng Thank you for using my script. Could you please try using the script downloaded from the following URL: https://raw.githubusercontent.com/ototadana/sd-face-editor/main/scripts/face_editor.py

That's great. It was a success this time

Thank you for your reply and your work
