### ISSUE TITLE
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by 777777lkj** [ototadana/sd-face-editor#120]
This issue occurred when updating to the latest version

To create a public link, set `share=True` in `launch()`.
Startup time: 11.2s (import torch: 1.0s, import gradio: 0.7s, import ldm: 0.3s, other imports: 0.6s, load scripts: 3.3s, create ui: 2.9s, gradio launch: 2.4s).
number of faces: 1
prompt for the face: <lora:face (1):1>
Traceback (most recent call last):
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\components.py", line 4457, in postprocess
    file = self.img_array_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\components.py", line 355, in img_array_to_temp_file
    return self.pil_to_temp_file(pil_image, dir, format="png")
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
number of faces: 1
prompt for the face: <lora:face (1):1>
Traceback (most recent call last):
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    event_id = getattr(body, "event_id", None)
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    ):
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    output = []
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\components.py", line 4457, in postprocess
  File "D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\components.py", line 355, in img_array_to_temp_file
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by ototadana** [comment]
@777777lkj 
Thanks for the error report.

I have never seen this error before, so at this point I cannot imagine either the cause or the solution.

If there is a case where the error does not occur, could you please tell me the difference in settings and environment from that case? If you can give me that information, I may be able to reproduce the phenomenon and determine the cause from that information.

**Comment by iamrohitanshu** [comment]
@ototadana I'm not entirely sure, but I think this problem is not with this extension, but the webui instead.
Many other extensions have the same issue.
For example, you might wanna check out https://github.com/opparco/stable-diffusion-webui-two-shot/issues/54#issuecomment-1585055946

**Comment by ototadana** [comment]
@iamrohitanshu 
Thanks!
Just now I was looking at that too.

The cause seems to be that the def save_pil_to_file method overridden by SD Web UI (-1.3.2) does not match the arguments required by gradio.

- https://github.com/gradio-app/gradio/blob/b51112811c3f3d689c80994695f8919c9cee8620/gradio/components.py#L355
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/baf6946e06249c5af9851c60171692c44ef633e0/modules/ui_tempdir.py#L34C5- L34C21

However, the latest version of the Web UI (1.4.0) has the following fixes and should work fine.

- https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8/modules/ui_tempdir.py#L34

I am not sure why this problem is occurring. It may be a distribution-specific problem that does not occur with the original Web UI.

@777777lkj @player99963
If your Web UI version is not 1.4.0, please try upgrading. I think there is a good chance that this problem can be solved.

**Comment by player99963** [comment]
> If your Web UI version is not 1.4.0, please try upgrading. I think there is a good chance that this problem can be solved.

After testing, the problems have all been solved.
Thank you for your efforts.
