### ISSUE TITLE
I met some difficulties and mistakes

### ISSUE THREAD

**Issue by MihuoUSA** [ototadana/sd-face-editor#129]
I am very sorry for my poor English. I hope you can understand me.
sd-face-editor The installation is normal and the use is normal, but the final picture will not be saved, and the error message shown in the background is as follows:
*** Error running postprocess: D:\Stable Diffusion\extensions\sd-face-editor\scripts\face_editor_extension.py
Traceback (most recent call last):
File "D:\Stable Diffusion\modules\scripts.py", line 498, in postprocess
script.postprocess(p, processed, *script_args)
File "D:\Stable Diffusion\extensions\sd-face-editor\scripts\face_editor_extension.py", line 53, in postprocess
ImageProcessor(WorkflowManager.get(option.workflow)).proc_images(o, res, option)
File "D:\Stable Diffusion\extensions\sd-face-editor\scripts\use_cases\workflow_manager.py", line 29, in get
raise KeyError(f"mask_generator {job.mask_generator.name} does not exist")
KeyError: 'mask_generator bisenet does not exist'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
————————————————————————————————————
SD1.5，python: 3.10.11 • torch: 2.0.1+cu118 • xformers: 0.0.20 • gradio: 3.32.0

Hope to get your help, thank you~~

**Comment by ototadana** [comment]
@MihuoUSA 
Thanks for the error report.

There must be another error when starting the Web UI, can you give me that information?

**Comment by MihuoUSA** [comment]
@ototadana 
Thank you very much for your timely reply, Indeed, as you said, there was an error message during startup.
The information is as follows:
Installing requirements

Launching Web UI with arguments: --lowvram --theme dark --xformers --opt-channelslast --api --autolaunch
[-] ADetailer initialized. version: 23.7.5, num models: 9
Traceback (most recent call last):
  File "C:\Stable Diffusion\extensions\sd-face-editor\scripts\use_cases\registry.py", line 14, in create
    c = cls()
  File "C:\Stable Diffusion\extensions\sd-face-editor\scripts\inferencers\bisenet_mask_generator.py", line 17, in __init__
    self.mask_model = init_parsing_model(device=shared.device)
  File "C:\Stable Diffusion\py310\lib\site-packages\facexlib\parsing\__init__.py", line 20, in init_parsing_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\Stable Diffusion\modules\safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "C:\Stable Diffusion\modules\safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Stable Diffusion\py310\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Stable Diffusion\py310\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 2499127 more bytes. The file might be corrupted.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Face Editor: <class 'module.name.BiSeNetMaskGenerator'>, Error: unexpected EOF, expected 2499127 more bytes. The file might be corrupted.
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
2023-07-12 12:33:57,260 - ControlNet - INFO - ControlNet v1.1.232
ControlNet preprocessor location: C:\Stable Diffusion\extensions\sd-webui-controlnet\annotator\downloads
2023-07-12 12:33:57,346 - ControlNet - INFO - ControlNet v1.1.232
Loading weights [1d3acbf755] from C:\Stable Diffusion\models\Stable-diffusion\sexSexyEasternExperienceV3_sexV30.safetensors
Creating model from config: C:\Stable Diffusion\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
No Image data blocks found.
Running on local URL:  http://127.0.0.1:7860

**Comment by ototadana** [comment]
@MihuoUSA 
This is the same problem as #112.

Deleting all files under the "C:\Stable Diffusion\models\GFPGAN" folder and restarting the Web UI will most likely fix the problem. If you still get the same error, follow [#112](https://github.com/ototadana/sd-face-editor/issues/112#issuecomment-1620068856) to manually download the files and place them in the "C:\Stable Diffusion\models\GFPGAN" folder.

**Comment by MihuoUSA** [comment]
@ototadana 
Following your guidelines, this problem, which has been bothering me for a long time, is completely solved! Thank you very much for your help!
I will close the issue and thank you again!
