### ISSUE TITLE
AttributeError: 'Dropdown' object has no attribute 'input'

### ISSUE THREAD

**Issue by wlchn** [ototadana/sd-face-editor#144]
Error happened after install face-editor. I have tried reload and restard sd-webui, but it still not work.

logs
```
Error calling: /root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py/ui
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py", line 23, in ui
    components = builder.build(is_img2img)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 23, in build
    components = [enabled] + self.__build(workflow_selector)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 162, in __build
    workflow = workflow_editor.build(workflow_selector)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/workflow_editor.py", line 103, in build
    filename_dropdown.input(load_workflow, inputs=[filename_dropdown], outputs=[workflow_editor])
AttributeError: 'Dropdown' object has no attribute 'input'

Error calling: /root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor.py/ui
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor.py", line 20, in ui
    components = builder.build(is_img2img)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 27, in build
    return self.__build(self.__create_workflow_selector())
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 162, in __build
    workflow = workflow_editor.build(workflow_selector)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/workflow_editor.py", line 103, in build
    filename_dropdown.input(load_workflow, inputs=[filename_dropdown], outputs=[workflow_editor])
AttributeError: 'Dropdown' object has no attribute 'input'

Create LRU cache (max_size=16) for preprocessor results.
Error calling: /root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py/ui
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py", line 23, in ui
    components = builder.build(is_img2img)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 23, in build
    components = [enabled] + self.__build(workflow_selector)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 162, in __build
    workflow = workflow_editor.build(workflow_selector)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/workflow_editor.py", line 103, in build
    filename_dropdown.input(load_workflow, inputs=[filename_dropdown], outputs=[workflow_editor])
AttributeError: 'Dropdown' object has no attribute 'input'

Error calling: /root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor.py/ui
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor.py", line 20, in ui
    components = builder.build(is_img2img)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 27, in build
    return self.__build(self.__create_workflow_selector())
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/ui_builder.py", line 162, in __build
    workflow = workflow_editor.build(workflow_selector)
  File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/ui/workflow_editor.py", line 103, in build
    filename_dropdown.input(load_workflow, inputs=[filename_dropdown], outputs=[workflow_editor])
AttributeError: 'Dropdown' object has no attribute 'input'

Running on local URL:  http://0.0.0.0:7860
```

**Comment by ototadana** [comment]
Perhaps the version of the Web UI is old. Try bringing it up to date.

See: #122

**Comment by wlchn** [comment]
OK, Resolved by Updated SD-Webui to latest version.
