### ISSUE TITLE
ValueError: images do not match

### ISSUE THREAD

**Issue by Datou** [ototadana/sd-face-editor#15]
It can complete the facial repair work excellently, but it will report an error during operation.

```
number of faces: 1
100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:01<00:00, 10.65it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  9.67it/s]
Error completing request:39,  1.07it/s]
Arguments: ('task(8qx7mze6oljsi4q)', 0, 'oilpaint,Sexy Dakotaskye smiling at you, (night-time:1.4) rave, (realistic face:1.3), (long hair),(Busty:1.3),(underboob:1.2), tight abs, (navel piercing:1.2), dancing on stage,low cut latex hotpants, cameltoe, perfect body, deep tan, happy expression, hand on hip, High Contrast, volumetric lighting, candid, Photograph, high resolution, 4k, 8k, Bokeh,((white sports bra)),((white shoes)),((black pants))', '3d, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), low-res, normal quality, ((monochrome)), ((grayscale)), skin spots, acne, skin blemishes, bad anatomy, ((child)) ((loli)), tattoos, bad_prompt_version2, ng_deepnegative_v1_75t, (asian.1.2) bad-hands-5, handbag, Poorly drawn hands, ((too many fingers)), ((bad fingers)) bad-image-v2-39000,((nsfw)),naked,nude,breast,((Gloves)),((t-shirt)),((shirt))\n', [], <PIL.Image.Image image mode=RGBA size=540x960 at 0x1A190A1BA90>, None, None, None, None, None, None, 27, 16, 4, 0, 1, False, False, 1, 1, 6.5, 1.5, 0.85, 4128014353.0, -1.0, 0, 0, 0, False, 960, 540, 0, 0, 32, 0, '', '', '', [], 1, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.external_code.ControlNetUnit object at 0x000001A2015215D0>, <scripts.external_code.ControlNetUnit object at 0x000001A201521060>, <scripts.external_code.ControlNetUnit object at 0x000001A201521C60>, <scripts.external_code.ControlNetUnit object at 0x000001A201548760>, <scripts.external_code.ControlNetUnit object at 0x000001A201549660>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, 1.6, 0.97, 0.4, 0.15, 20, 0, 0, '', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', 'None', '', '', 1, 'FirstGen', False, False, 'InputFrame', False,   1 2 3
0      , False, '', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '', '', 20.0, '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\img2img.py", line 170, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "F:\stable-diffusion-webui\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "F:\stable-diffusion-webui\scripts\face_editor.py", line 167, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "F:\stable-diffusion-webui\scripts\face_editor.py", line 271, in __proc_image
    proc = process_images(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 711, in process_images_inner
    image_mask_composite = Image.composite(image.convert('RGBA').convert('RGBa'), Image.new('RGBa', image.size), p.mask_for_overlay.convert('L')).convert('RGBA')
  File "F:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3341, in composite
    image.paste(image1, None, mask)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1731, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match

```

![image](https://user-images.githubusercontent.com/15013/231923208-27a36d5e-19d9-42cd-a2b0-a6e5488195cc.png)
![image](https://user-images.githubusercontent.com/15013/231923230-f3791916-2c68-487f-be19-ee2995d6cad1.png)

**Comment by ototadana** [comment]
Thanks for the error report :smiley: 
A fix has been implemented and the error should no longer occur.

**Comment by Datou** [comment]
Thank you very much! It works!
![image](https://user-images.githubusercontent.com/15013/232192892-a3597d58-9943-4f5a-adcd-4cdcf667c3e9.png)
