### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by amytong85** [ototadana/sd-face-editor#168]
*** Error running postprocess: /root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py
    Traceback (most recent call last):
      File "/root/stable-diffusion-webui/modules/scripts.py", line 551, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py", line 53, in postprocess
        ImageProcessor(WorkflowManager.get(option.workflow)).proc_images(o, res, option)
      File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/use_cases/image_processor.py", line 62, in proc_images
        proc = self.proc_image(p, option, image, res.infotexts[i], (res.width, res.height))
      File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/use_cases/image_processor.py", line 176, in proc_image
        proc_image = self.workflow.process(jobs, face, p, option)
      File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/use_cases/workflow_manager.py", line 162, in process
        image = face_processor.process(face, p, **params)
      File "/root/stable-diffusion-webui/extensions/sd-face-editor/scripts/inferencers/img2img_face_processor.py", line 35, in process
        refiner_switch_at = p.refiner_switch_at
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'refiner_switch_at'

i'm using latest version of face editor,and webui 1.6,but it dosen't work

**Comment by ototadana** [comment]
@amytong85 
If the Web UI version is 1.6.0, this error should not appear, so could you please check the version?
If this error occurs even though the version is 1.6.0, we need to identify the conditions under which it occurs, so can you give me  more detailed information?

**Comment by amytong85** [comment]
I'm using cloud server from there[https://www.codewithgpu.com/i/AUTOMATIC1111/stable-diffusion-webui/tzwm_sd_webui_A1111](url),
and it says：AUTOMATIC1111/stable-diffusion-webui [v1.6.0]
Python 3.10.6 + Torch 2.0.1 + cuda 11.8 + xformers 0.0.20.
There is no free service, so if you can't get enough information, maybe I can go and ask author😀.

**Comment by ototadana** [comment]
Thanks for the info. Maybe it is a special derivative version. 

I have made a modification to make it as error-free as possible when running on such a version, so could you please try it?

**Comment by amytong85** [comment]
![image](https://github.com/ototadana/sd-face-editor/assets/126079848/970a86d6-b91a-40bb-91b9-9ea074b04c59)
It works! thanks for your help！
