### ISSUE TITLE
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)

### ISSUE THREAD

**Issue by swumagic** [ototadana/sd-face-editor#175]
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 25, in <module>
        from modules.reactor_mask import apply_face_mask
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\modules\reactor_mask.py", line 9, in <module>
        from scripts.entities.face import FaceArea
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 31, in <module>
        from scripts.reactor_swapper import (
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 25, in <module>
        from modules.reactor_mask import apply_face_mask
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\modules\reactor_mask.py", line 9, in <module>
        from scripts.entities.face import FaceArea
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 25, in <module>
        from modules.reactor_mask import apply_face_mask
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\modules\reactor_mask.py", line 9, in <module>
        from scripts.entities.face import FaceArea
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by ototadana** [comment]
@swumagic 
This error seems to be caused by a module in sd-webui-reactor that has the same name as sd-face-editor.
(I checked [the source code](https://github.com/Gourieff/sd-webui-reactor/blob/2c2d40508a519c5f7d65fa48cef8409456f324d3/scripts/entities/face.py) and it seems that the module with the same name is based on [the source code of sd-face-editor](https://github.com/ototadana/sd-face-editor/blob/557dc3bec0ed6f5a0f7fdc19b3efbc1fd65e8328/scripts/entities/face.py))

There is nothing I can do about it, so please watch for a response to [this Issue that you submitted](https://github.com/Gourieff/sd-webui-reactor/issues/211).

**Comment by swumagic** [comment]
Thank you!

**Comment by swumagic** [comment]
Feedback to the author of sd-webui-reactor  to reply and fix this BUG。

**Comment by Gourieff** [comment]
> Feedback to the author of sd-webui-reactor to reply and fix this BUG。

Fixed

> (I checked [the source code](https://github.com/Gourieff/sd-webui-reactor/blob/2c2d40508a519c5f7d65fa48cef8409456f324d3/scripts/entities/face.py) and it seems that the module with the same name is based on [the source code of sd-face-editor](https://github.com/ototadana/sd-face-editor/blob/557dc3bec0ed6f5a0f7fdc19b3efbc1fd65e8328/scripts/entities/face.py))

@ototadana Thanks for your wonderful extension! I mentioned you as the Contributor for released version https://github.com/Gourieff/sd-webui-reactor/releases/tag/v0.5.1
