### ISSUE TITLE
 Error loading script: face_editor.py

### ISSUE THREAD

**Issue by JediMaDMZ** [ototadana/sd-face-editor#188]
I'm having this problem lately

*** Error loading script: face_editor.py
    Traceback (most recent call last):
      File "I:\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "I:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "I:\AI\stable-diffusion-webui\scripts\face_editor.py", line 5, in <module>
        from scripts.entities.option import Option
    ModuleNotFoundError: No module named 'scripts.entities'

How can I fix it please?

**Comment by ototadana** [comment]
It appears to be installed using a very old version of the setup instructions.
Could you please remove face-editor.py from "I:\AI\stable-diffusion-webui\scripts\" and reinstall it following the instructions below?
- https://github.com/ototadana/sd-face-editor?tab=readme-ov-file#setup

**Comment by JediMaDMZ** [comment]
Solved, thank you so much !

**Comment by JediMaDMZ** [comment]
Solved! thank you so much!
