### ISSUE TITLE
Error loading script: face_editor.py

### ISSUE THREAD

**Issue by siriusyxd** [ototadana/sd-face-editor#191]
When I tried to install the sd_face_editor plugin for stable diffusion, the following error message appeared:
 ***Error loading script: face_editor.py
    Traceback (most recent call last):
      File "E:\WebUI\stable-diffusion\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\WebUI\stable-diffusion\webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\WebUI\stable-diffusion\webui\scripts\face_editor.py", line 5, in <module>
        from scripts.entities.option import Option
    ModuleNotFoundError: No module named 'scripts.entities'

---
*** Error loading script: face_editor.py
    Traceback (most recent call last):
      File "E:\WebUI\stable-diffusion\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\WebUI\stable-diffusion\webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\WebUI\stable-diffusion\webui\extensions\sd-face-editor\scripts\face_editor.py", line 6, in <module>
        from scripts.ui.ui_builder import UiBuilder
    ModuleNotFoundError: No module named 'scripts.ui.ui_builder'; 'scripts.ui' is not a package

---
*** Error loading script: face_editor_extension.py
    Traceback (most recent call last):
      File "E:\WebUI\stable-diffusion\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\WebUI\stable-diffusion\webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\WebUI\stable-diffusion\webui\extensions\sd-face-editor\scripts\face_editor_extension.py", line 5, in <module>
        from scripts.ui.ui_builder import UiBuilder
    ModuleNotFoundError: No module named 'scripts.ui.ui_builder'; 'scripts.ui' is not a package

---

Could you please advise on how to resolve this issue? Thank you all.

**Comment by siriusyxd** [comment]
I modified the code according to your docs,and it worked.Thank you very much @ototadana   :-)
