### ISSUE TITLE
idk if amd user can use this

### ISSUE THREAD

**Issue by sorryhorizonTT** [ototadana/sd-face-editor#21]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 175, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 222, in __proc_image
    faces = self.__crop_face(
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 308, in __crop_face
    face_boxes, _ = detection_model.align_multi(image, confidence)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\facexlib\detection\retinaface.py", line 255, in align_multi
    rlt = self.detect_faces(img, conf_threshold=conf_threshold)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\facexlib\detection\retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\facexlib\detection\retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\facexlib\detection\retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torchvision\models\_utils.py", line 69, in forward
    x = module(x)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (PrivateUse1FloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by ototadana** [comment]
@sorryhorizonTT 
Thanks for the error report 😍

Unfortunately, I am not an AMD user and cannot reproduce this error. However, based on the error message you reported, I have tried to guess the cause of the error and have made a fix for it.
Could you please try the new version?

**Comment by sorryhorizonTT** [comment]
@ototadana 
Thank u for replying so quickly
here comes an another error


To create a public link, set `share=True` in `launch()`.
Error completing request
Arguments: ('task(vtf5kkgzuagocaq)', 0, 'realistic, 8k,raw photo,', 'easynegative', [], <PIL.Image.Image image mode=RGBA size=512x768 at 0x2332FA48340>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 768, 512, 0, 0, 32, 0, '', '', '', [], 9, False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, False, True, True, False, 512, 64, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, 1.6, 0.97, 0.4, 0.15, 20, 0, 0, '', False, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 178, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 225, in __proc_image
    faces = self.__crop_face(
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 311, in __crop_face
    face_boxes, _ = detection_model.align_multi(image, confidence)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\facexlib\detection\retinaface.py", line 255, in align_multi
    rlt = self.detect_faces(img, conf_threshold=conf_threshold)
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\facexlib\detection\retinaface.py", line 203, in detect_faces
    image = image - self.mean_tensor
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, privateuseone:0 and cpu!

**Comment by ototadana** [comment]
@sorryhorizonTT 
Thanks for trying it so quickly. 
I saw the error message you reported and have implemented the fix again.
Thank you for your patience, but could you please try again?

**Comment by sorryhorizonTT** [comment]
@ototadana OHHHHHHHHH it is working correctly now
thank u so much
u r so good

**Comment by sorryhorizonTT** [comment]
@ototadana 
another one
AMD NO !

Arguments: ('task(xvknv5i0rlh8ois)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=512x768 at 0x2BD3114A320>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 9, False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, False, True, True, False, 512, 64, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, 1.6, 0.97, 0.4, 0.15, 20, 0, 0, '', False, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 178, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 261, in __proc_image
    mask_image = self.__to_mask_image(
  File "D:\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 328, in __to_mask_image
    face_tensor = torch.unsqueeze(face_tensor, 0).cuda()
  File "D:\stable-diffusion-webui\Python3.10\lib\site-packages\torch\cuda\__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by sorryhorizonTT** [comment]
![image](https://user-images.githubusercontent.com/130207576/232235599-4102356f-ee1a-461a-816f-a80b41e01ed8.png)

but it was running correctly at first

**Comment by ototadana** [comment]
@sorryhorizonTT 
Thanks for trying so many times.
I have made a correction to the error in the report you provided.
I wish it success this time.

**Comment by sorryhorizonTT** [comment]
@ototadana OHHHHHHHHH thank u so much
it is working correctly now

**Comment by ototadana** [comment]
@sorryhorizonTT 
I am very happy that it works well!
Thank you very much :heart:
