### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by LinXudong** [ototadana/sd-face-editor#24]
Traceback (most recent call last):
  File "D:\GitCode\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\GitCode\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\GitCode\stable-diffusion-webui\modules\img2img.py", line 170, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\GitCode\stable-diffusion-webui\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "D:\GitCode\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 178, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "D:\GitCode\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 261, in __proc_image
    mask_image = self.__to_mask_image(
  File "D:\GitCode\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 327, in __to_mask_image
    normalize(face_tensor, (0.5, 0.5, 0.5), (0.5, 0.5, 0.5), inplace=True)
  File "D:\GitCode\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\functional.py", line 363, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "D:\GitCode\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\_functional_tensor.py", line 928, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by ototadana** [comment]
@LinXudong 
Thanks for the error report.
Unfortunately I could not reproduce this error. However, I deduced the cause of the error from the error message you reported and added a process to prevent it.
Could you please check the operation with the new version?

**Comment by DreamError404** [comment]
> @LinXudong Thanks for the error report. Unfortunately I could not reproduce this error. However, I deduced the cause of the error from the error message you reported and added a process to prevent it. Could you please check the operation with the new version?

I had this problem before.Now this version is good. Thanks a lot!

**Comment by LinXudong** [comment]
Very good, the current version has resolved this issue. Thank you for the author's efforts.
