### ISSUE TITLE
RuntimeError: unexpected EOF, expected 3194323 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by foxender** [ototadana/sd-face-editor#47]
like this code, when i use face editor it will be error

**Comment by foxender** [comment]
Error completing request
Arguments: ('task(dbw4nlggrz7thlg)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 4, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, False, '', 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x0000028DAD7392A0>, <scripts.external_code.ControlNetUnit object at 0x0000028DAD738A60>, <scripts.external_code.ControlNetUnit object at 0x0000028DAD73BB50>, <scripts.external_code.ControlNetUnit object at 0x0000028DAD73BBB0>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 1.6, 0.97, 0.4, 0.15, 20, 0, 0, '', False, False, False, False, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-face-editor\scripts\face_editor.py", line 192, in run
    mask_model = init_parsing_model(device=shared.device)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\facexlib\parsing\__init__.py", line 20, in init_parsing_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\safe.py", line 107, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\modules\safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 3194323 more bytes. The file might be corrupted.

**Comment by ototadana** [comment]
@foxender 
Perhaps the "D:\tools\sd-webui-aki\sd-webui-aki-v4\sd-webui-aki-v4\models\GFPGAN\parsing_bisenet.pth" file is corrupt, so delete that file first, then try again.

**Comment by foxender** [comment]
this work. thx u
