### ISSUE TITLE
is it possible to add a switch that do not edit faces more than 512*512?

### ISSUE THREAD

**Issue by werran2** [ototadana/sd-face-editor#65]
As to the big pics which faces pixs are lager that 512, it may generate a worse img.
thank you for your efforts and I like it.

**Comment by ototadana** [comment]
@werran2 
I see...that may be so.

I wanted to see how size affects the creation of a face image, so I added a "Size of the face when recreating" option.

Maybe this will improve face images larger than 512*512 pixels. (Or it may not improve at all...)

**Comment by ototadana** [comment]
@werran2 
I added an option to ignore if the size of the detected face is larger than the size specified in "Size of the face when recreating."
Please try it!

**Comment by werran2** [comment]
> @werran2 I added an option to ignore if the size of the detected face is larger than the size specified in "Size of the face when recreating." Please try it!

it works great! thank you
and for the 1st option, 768 and 1024 pix also works fine
great job

**Comment by werran2** [comment]
Got an error with sampler DPM++ 2M SDE Karras specifically, not test all samplers, but DPM++ 2M karras and  DPM++ SDE karras works fine.

Traceback (most recent call last):
  File "C:\novelai-webui-aki-v3\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\novelai-webui-aki-v3\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\novelai-webui-aki-v3\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\novelai-webui-aki-v3\modules\scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "C:\novelai-webui-aki-v3\extensions\sd-face-editor\scripts\face_editor.py", line 257, in run
    return self.proc_images(mask_model, detection_model, o, res,
  File "C:\novelai-webui-aki-v3\extensions\sd-face-editor\scripts\face_editor.py", line 310, in proc_images
    proc = self.__proc_image(p, mask_model, detection_model,
  File "C:\novelai-webui-aki-v3\extensions\sd-face-editor\scripts\face_editor.py", line 465, in __proc_image
    proc = process_images(p)
  File "C:\novelai-webui-aki-v3\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "C:\novelai-webui-aki-v3\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\novelai-webui-aki-v3\modules\processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\novelai-webui-aki-v3\modules\processing.py", line 1262, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "C:\novelai-webui-aki-v3\modules\sd_samplers_kdiffusion.py", line 356, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\novelai-webui-aki-v3\modules\sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "C:\novelai-webui-aki-v3\modules\sd_samplers_kdiffusion.py", line 356, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\novelai-webui-aki-v3\repositories\k-diffusion\k_diffusion\sampling.py", line 650, in sample_dpmpp_2m_sde
    h_last = h
UnboundLocalError: local variable 'h' referenced before assignment
