### ISSUE TITLE
`UnboundLocalError: local variable 'h' referenced before assignment`

### ISSUE THREAD

**Issue by ElPrudi** [ototadana/sd-face-editor#74]
Just found your extension and wanted to try it out. Sadly, even with the recommended setting, I can't get this to work, because I get this error on text2img:

```
Error running postprocess: D:\AIUI\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor_extension.py
Traceback (most recent call last):
  File "D:\AIUI\stable-diffusion-webui\modules\scripts.py", line 478, in postprocess
    script.postprocess(p, processed, *script_args)
  File "D:\AIUI\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor_extension.py", line 98, in postprocess
    script.proc_images(mask_model, detection_model, o, res,
  File "D:\AIUI\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 321, in proc_images
    proc = self.__proc_image(p, mask_model, detection_model,
  File "D:\AIUI\stable-diffusion-webui\extensions\sd-face-editor\scripts\face_editor.py", line 479, in __proc_image
    proc = process_images(p)
  File "D:\AIUI\stable-diffusion-webui\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "D:\AIUI\stable-diffusion-webui\modules\processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\AIUI\stable-diffusion-webui\modules\processing.py", line 1262, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\AIUI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 356, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\AIUI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "D:\AIUI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 356, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\AIUI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIUI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 650, in sample_dpmpp_2m_sde
    h_last = h
UnboundLocalError: local variable 'h' referenced before assignment
```

I use Web UI 1.3.0

**Comment by ototadana** [comment]
@ElPrudi 
Thanks for using this script.

According to the error message you gave me, it looked like the problem occurs when "DPM++ 2M SDE" is selected as the sampling method.

As a workaround, I found that the error can be avoided by either of the following methods.

- Use another sampling method
- Set "Denoising strength for the entire image" to a value greater than 0

Please give it a try.

**Comment by ElPrudi** [comment]
Both workarounds work. I changed 2M SDE to 2M and it worked. I also tried 2M SDE with the full image denoising strength and it worked. For some reason the first method outputs two images. One before processing and one after.

**Comment by ototadana** [comment]
@ElPrudi 

I noticed that if "Denoising strength for the entire image" is zero, there is no need to process the image. So, I rewrote the code to skip processing in that case. As a result, the error does not occur even when "DPM++ 2M SDE" is selected.

> For some reason the first method outputs two images. One before processing and one after.

If you see two images on the disk, it may be that the "Save original image" option is turned on.
