### ISSUE TITLE
Using the script in img2img mode through the API possibly broken

### ISSUE THREAD

**Issue by anti-matt-er** [ototadana/sd-face-editor#90]
Hi there!

First of all, thank you for this wonderful extension - it does exactly what I need it to do.

There seems to be a small issue when using the API in img2img mode (with the script, NOT the extension version).

First of all, here's the relevant part from my JSON payload, roughly corresponding to the defaults from the UI:

```
"script_name": "face editor",
"script_args": [1.6, 0.97, 0.4, 0, 20, 0, 12, "angry", true, false, false, false, 512, true, true]
```

As it is, this returns a 500 "Internal Server Error" and produces the following traceback in the console:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\StableDiffusion\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\StableDiffusion\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "C:\StableDiffusion\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\StableDiffusion\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\StableDiffusion\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\StableDiffusion\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\StableDiffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\StableDiffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\StableDiffusion\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\StableDiffusion\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\StableDiffusion\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\StableDiffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\StableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\StableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\StableDiffusion\modules\api\api.py", line 244, in img2imgapi
    processed = scripts.scripts_img2img.run(p, *p.script_args)
  File "C:\StableDiffusion\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "C:\StableDiffusion\extensions\sd-face-editor\scripts\face_editor.py", line 257, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "C:\StableDiffusion\extensions\sd-face-editor\scripts\face_editor.py", line 427, in __proc_image
    for script in p.scripts.alwayson_scripts:
AttributeError: 'NoneType' object has no attribute 'alwayson_scripts'
```

As of the latest commit, this is no longer line 427 but 437 - though this part seems unchanged so I don't believe updating will solve this for me. Here's the relevant lines from the latest commit:

https://github.com/ototadana/sd-face-editor/blob/136f90637496d34f6ed674f330b9dca2a5eda65b/scripts/face_editor.py#L437-L439

I have a workaround but it seems hacky and probably not the best solution, I simply ignore the exception using a `try / except` block:

```
try:
    for script in p.scripts.alwayson_scripts:
        if script.filename.endswith("stable-diffusion-webui-wildcards/scripts/wildcards.py"):
            wildcards_script = script
except:
    pass
```

This fixes the issue and the returned image is now precisely the same as the result I get from using the WebUI. It's possible that the issue is caused by me not using the wildcards extension (I have no need for it), but I'm unsure.

I could open a PR for this, but I'm very wary of whether or not this will have repercussions elsewhere for other users, so I'd like to see your thoughts first.

One last thing, for anyone else who wants to use the script via API, `apply_scripts_to_faces` must be set to false, and the order of the `script_args` array corresponds to the following parameters:

```
face_margin
confidence
strength1
strength2
max_face_count
mask_size
mask_blur
prompt_for_face
apply_inside_mask_only
save_original_image
show_intermediate_steps
apply_scripts_to_faces
face_size
use_minimal_area
ignore_larger_faces
```

Thanks again for this wonderful extension!

**Comment by ototadana** [comment]
#95 to fix this error. 

In addition, scripts can now specify parameters as object (dict), which should be as convenient as extensions.
For more information, click [here](https://github.com/ototadana/sd-face-editor#api).

**Comment by anti-matt-er** [comment]
Thank you for this! I ended up being too busy to address this, my workflow is quite different now - but I'll update and test later on :)
