### ISSUE TITLE
Can not display processed image with webui 1.3.2

### ISSUE THREAD

**Issue by ElPrudi** [ototadana/sd-face-editor#91]
Your extension still works wonderfully! But, with the new version of the webui, 1.3.2, I get this error
```
Traceback (most recent call last):s/it]
  File "D:\AIUI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AIUI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\AIUI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\AIUI\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "D:\AIUI\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "...\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "...\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File " ...\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '...\\AppData\\Local\\Temp\\gradio\\tmprp5_bug1.png'
```

I obscured the path with current users path with `...`. It doesn't occur when it's turned off.

This error only affects only the preview. There is no error during the processing.

**Comment by ototadana** [comment]
@ElPrudi 

Thanks for the error report!

I also got the same error after upgrading to 1.3.2. I added a workaround for this error.

Please try it.

**Comment by ElPrudi** [comment]
Can confirm, it works again.

Thank you very much :D
